### ISSUE TITLE
color of the Handler

### ISSUE THREAD

**Issue by romanown** [react-component/drawer#19]
https://codesandbox.io/s/9z3zrz3814
I can not changing color of the Handler. [X] in the sample is black but i need the wihte when drawer is opened.

**Comment by jljsj33** [comment]
```css
.drawer-handle {
  color: "#00f"
}
```
